/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.TCSistemaControlador;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author RyuujiMD
 */
public class EjecutarSQL extends javax.swing.JInternalFrame {

    /**
     * Creates new form EjecutarSQL
     */
    public EjecutarSQL() {
        initComponents();
    }

    private final TCSistemaControlador tcsc = TCSistemaControlador.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSQL = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ALDOFOFOFOFO");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("SQL:");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        txtSQL.setColumns(20);
        txtSQL.setRows(5);
        jScrollPane1.setViewportView(txtSQL);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            EntityManager em = tcsc.getDao().getEntityManager();
            em.getTransaction().begin();
            em.createNativeQuery(txtSQL.getText()).executeUpdate();
            em.getTransaction().commit();
            em.clear();
            JOptionPane.showMessageDialog(this, "HECHO");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSQL;
    // End of variables declaration//GEN-END:variables
}
